const body = `
<body style="padding: 40px">
  <h1>
    <a style="text-decoration: none;" href="http://nginx.org/en/docs/http/ngx_http_ssi_module.html">SSI</a>
  </h1>
  <h2>Nginx SSI module is a filter that processes SSI commands in responses passing through it.</h2>
</body>
`;

const footer = `
<footer>
  <p style="color: #999">
    This markup was generated by TencentCloud EdgeFunctions with SSI.
  </p>
</footer>
`;

async function handleSSI(html) {
  const ssiRegex = /<!--#include virtual="(.+?)" -->/g;
  const replacements = {
    '/body.html': body,
    '/footer.html': footer,
  };

  return html.replace(ssiRegex, (_, includePath) => {
    return replacements[includePath] || '';
  });
}

async function handleEvent(event) {
  const html = `
<!DOCTYPE html>
<html>
  <head>
    <title>ESR - SSI - EdgeFunctions</title>
  </head>
  <!--#include virtual="/body.html" -->
  <!--#include virtual="/footer.html" -->
</html>
`;

  const processedHtml = await handleSSI(html);

  const res = new Response(processedHtml, {
    headers: { 'Content-Type': 'text/html' },
  });

  event.respondWith(res);
}

addEventListener('fetch', handleEvent);
