import React from 'react';
import { Link } from 'react-router-dom';

import logger from '../utils/logger';

function Home() {
  logger.log('Home render!');

  return (
    <div>
      <h1>
        <a style={{ textDecoration: 'none' }} href="https://react.dev/">
          React
        </a>
        <span style={{ margin: '0 10px' }}>+</span>
        <a style={{ textDecoration: 'none' }} href="https://react.dev/reference/react-dom/server">
          Server React DOM APIs
        </a>
        <span style={{ margin: '0 10px' }}>+</span>
        <a style={{ textDecoration: 'none' }} href="https://react.dev/reference/react-dom/client/hydrateRoot">
          Hybrate
        </a>
      </h1>
      <h2>React lets you build user interfaces out of individual pieces called components.</h2>
      <h2>
        The <code>react-dom/server</code> APIs let you render React components to HTML on the server.
      </h2>
      <p style={{ color: '#999' }}>This markup was generated by TencentCloud EdgeFunctions with React.</p>
      <Link to="/blog">Blog page</Link>
    </div>
  );
}

export default Home;
