import React, { Suspense, lazy } from 'react';
import { Link } from 'react-router-dom';

import logger from '../utils/logger';

const LazyContent = lazy(() => import('./Content'));

function Blog() {
  logger.log('Blog render!');

  return (
    <div>
      <h1>Blog</h1>
      <Suspense fallback={<div>Loading...</div>}>
        <LazyContent />
      </Suspense>
      <p style={{ color: '#999' }}>This markup was generated by TencentCloud EdgeFunctions with React.</p>
      <Link to="/">Home page</Link>
    </div>
  );
}

export default Blog;
