const html = `
<!DOCTYPE html>
<html>
  <head>
    <title>ESR - HTML - EdgeFunctions</title>
  </head>
  <body style="padding: 40px">
    <h1>Hello EdgeFunctions</h1>
    <p style="color: #999">
      This markup was generated by TencentCloud EdgeFunctions.
    </p>
  </body>
</html>
`;

async function handleEvent(event) {
  const res = new Response(html, {
    headers: { 'Content-Type': 'text/html' },
  });

  event.respondWith(res);
}

addEventListener('fetch', handleEvent);
