import template from 'art-template/lib/template-web';

const tpl = `
<!DOCTYPE html>
<html>
  <head>
    <title><%= data.title %></title>
  </head>
  <body style="padding: 40px">
    <h1>
      <a style="text-decoration: none;" href="https://aui.github.io/art-template/"><%= data.h1 %></a>
    </h1>
    <h2><%= data.h2 %></h2>
    <p style="color: #999"><%= data.desc %></p>
  </body>
</html>
`;

function handleEvent(event) {
  const html = template.render(tpl, {
    data: {
      title: 'ESR - ART-TEMPLATE - EdgeFunctions',
      h1: 'ART-TEMPLATE',
      h2: 'High performance JavaScript templating engine',
      desc: 'This markup was generated by TencentCloud EdgeFunctions with art-template.',
    },
  });

  const res = new Response(html, {
    headers: { 'Content-Type': 'text/html' },
  });

  event.respondWith(res);
}

addEventListener('fetch', handleEvent);
