import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

import logger from '../utils/logger';

async function sleep() {
  const sleepUrl = 'https://www.fastmock.site/mock/b1f6a818687c1766c39d271da1ca0442/ef/sleep';
  await fetch(sleepUrl, { eo: { cacheTtl: 0 } });
}

function Blog() {
  logger.log('Blog render!');

  const [data, setData] = useState('Loading...');

  const fetchData = async () => {
    await sleep();
    setData('Blog Content');
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div>
      <h1>Blog</h1>
      <div>{data}</div>
      <p style={{ color: '#999' }}>This markup was generated by TencentCloud EdgeFunctions with React.</p>
      <Link to="/">Home page</Link>
    </div>
  );
}

export default Blog;
