async function sleep() {
  const sleepUrl = 'https://www.fastmock.site/mock/b1f6a818687c1766c39d271da1ca0442/ef/sleep';
  await fetch(sleepUrl, { eo: { cacheTtl: 0 } });
  return 'awake';
}

async function streamHTMLContent(writable) {
  const writer = writable.getWriter();

  await writer.write(`
<html>
  <head>
    <title>ESR - HTML-STREAM - EdgeFunctions</title>
  </head>
  <body style="padding: 40px">
    <h1>HTML Stream Rendering</h1>
    <div>First segment</div>
`);

  console.log(await sleep());
  await writer.write(`
    <div>Second segment</div>
    <p style="color: #999">
      This markup was generated by TencentCloud EdgeFunctions.
    </p>
  </body>
</html>`);

  await writer.close();
}

async function handleEvent(event) {
  const { readable, writable } = new TransformStream();

  streamHTMLContent(writable);

  const res = new Response(readable, {
    headers: { 'Content-Type': 'text/html' },
  });

  event.respondWith(res);
}

addEventListener('fetch', handleEvent);
